title: Sarah's Research
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sarah talks about her research here.
# social links
twitter_username: shashafeng3
github_username:  sha256feng

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
